package com.lottery.pojo;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

public class BuyModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_BUY.BID
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    private Short bid;
    private Short userid;
    private String isdraw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_BUY.BUYDATE
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    private Timestamp buydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_BUY.LOTTERID
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    private Short lotterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_BUY.BUYMONEY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    private BigDecimal buymoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_BUY.BUYNO
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    private String buyno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_BUY.BID
     *
     * @return the value of LOTTERY.T_BUY.BID
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public Short getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_BUY.BID
     *
     * @param bid the value for LOTTERY.T_BUY.BID
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public void setBid(Short bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_BUY.BUYDATE
     *
     * @return the value of LOTTERY.T_BUY.BUYDATE
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public Timestamp getBuydate() {
        return buydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_BUY.BUYDATE
     *
     * @param buydate the value for LOTTERY.T_BUY.BUYDATE
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public void setBuydate(Timestamp buydate) {
        this.buydate = buydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_BUY.LOTTERID
     *
     * @return the value of LOTTERY.T_BUY.LOTTERID
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public Short getLotterid() {
        return lotterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_BUY.LOTTERID
     *
     * @param lotterid the value for LOTTERY.T_BUY.LOTTERID
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public void setLotterid(Short lotterid) {
        this.lotterid = lotterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_BUY.BUYMONEY
     *
     * @return the value of LOTTERY.T_BUY.BUYMONEY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public BigDecimal getBuymoney() {
        return buymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_BUY.BUYMONEY
     *
     * @param buymoney the value for LOTTERY.T_BUY.BUYMONEY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public void setBuymoney(BigDecimal buymoney) {
        this.buymoney = buymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_BUY.BUYNO
     *
     * @return the value of LOTTERY.T_BUY.BUYNO
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public String getBuyno() {
        return buyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_BUY.BUYNO
     *
     * @param buyno the value for LOTTERY.T_BUY.BUYNO
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public void setBuyno(String buyno) {
        this.buyno = buyno;
    }

	public Short getUserid() {
		return userid;
	}

	public void setUserid(Short userid) {
		this.userid = userid;
	}

	@Override
	public String toString() {
		return "BuyModel [bid=" + bid + ", userid=" + userid + ", buydate=" + buydate + ", lotterid=" + lotterid
				+ ", buymoney=" + buymoney + ", buyno=" + buyno + "]";
	}

	public String getIsdraw() {
		return isdraw;
	}

	public void setIsdraw(String isdraw) {
		this.isdraw = isdraw;
	}
}