package com.lottery.pojo;

import java.math.BigDecimal;

public class DrawDetailsModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_DRAWDETAILS.DDID
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    private Short ddid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_DRAWDETAILS.LOTTERID
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    private Short lotterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_DRAWDETAILS.PRIZE
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    private String prize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_DRAWDETAILS.DRAWNUM
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    private BigDecimal drawnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_DRAWDETAILS.DRAWMONEY
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    private BigDecimal drawmoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_DRAWDETAILS.DDID
     *
     * @return the value of LOTTERY.T_DRAWDETAILS.DDID
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    public Short getDdid() {
        return ddid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_DRAWDETAILS.DDID
     *
     * @param ddid the value for LOTTERY.T_DRAWDETAILS.DDID
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    public void setDdid(Short ddid) {
        this.ddid = ddid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_DRAWDETAILS.LOTTERID
     *
     * @return the value of LOTTERY.T_DRAWDETAILS.LOTTERID
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    public Short getLotterid() {
        return lotterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_DRAWDETAILS.LOTTERID
     *
     * @param lotterid the value for LOTTERY.T_DRAWDETAILS.LOTTERID
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    public void setLotterid(Short lotterid) {
        this.lotterid = lotterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_DRAWDETAILS.PRIZE
     *
     * @return the value of LOTTERY.T_DRAWDETAILS.PRIZE
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    public String getPrize() {
        return prize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_DRAWDETAILS.PRIZE
     *
     * @param prize the value for LOTTERY.T_DRAWDETAILS.PRIZE
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    public void setPrize(String prize) {
        this.prize = prize == null ? null : prize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_DRAWDETAILS.DRAWNUM
     *
     * @return the value of LOTTERY.T_DRAWDETAILS.DRAWNUM
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    public BigDecimal getDrawnum() {
        return drawnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_DRAWDETAILS.DRAWNUM
     *
     * @param drawnum the value for LOTTERY.T_DRAWDETAILS.DRAWNUM
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    public void setDrawnum(BigDecimal drawnum) {
        this.drawnum = drawnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_DRAWDETAILS.DRAWMONEY
     *
     * @return the value of LOTTERY.T_DRAWDETAILS.DRAWMONEY
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    public BigDecimal getDrawmoney() {
        return drawmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_DRAWDETAILS.DRAWMONEY
     *
     * @param drawmoney the value for LOTTERY.T_DRAWDETAILS.DRAWMONEY
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    public void setDrawmoney(BigDecimal drawmoney) {
        this.drawmoney = drawmoney;
    }
}