package com.lottery.pojo;

import java.math.BigDecimal;
import java.sql.Timestamp;

public class LotteryModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_LOTTERY.LOTTERID
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    private Short lotterid;
    private BigDecimal totalsale;
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_LOTTERY.LID
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    private Short lid;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_LOTTERY.ACCUMULATED
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    private BigDecimal accumulated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_LOTTERY.STARTTIME
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    private Timestamp starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_LOTTERY.ISSUE
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    private String issue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_LOTTERY.DRAWMONEY
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    private BigDecimal drawmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_LOTTERY.DRAWNUM
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    private BigDecimal drawnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_LOTTERY.DRAWNO
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    private String drawno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_LOTTERY.LOTTERID
     *
     * @return the value of LOTTERY.T_LOTTERY.LOTTERID
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public Short getLotterid() {
        return lotterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_LOTTERY.LOTTERID
     *
     * @param lotterid the value for LOTTERY.T_LOTTERY.LOTTERID
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public void setLotterid(Short lotterid) {
        this.lotterid = lotterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_LOTTERY.LID
     *
     * @return the value of LOTTERY.T_LOTTERY.LID
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public Short getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_LOTTERY.LID
     *
     * @param lid the value for LOTTERY.T_LOTTERY.LID
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public void setLid(Short lid) {
        this.lid = lid;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_LOTTERY.ACCUMULATED
     *
     * @return the value of LOTTERY.T_LOTTERY.ACCUMULATED
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public BigDecimal getAccumulated() {
        return accumulated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_LOTTERY.ACCUMULATED
     *
     * @param accumulated the value for LOTTERY.T_LOTTERY.ACCUMULATED
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public void setAccumulated(BigDecimal accumulated) {
        this.accumulated = accumulated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_LOTTERY.STARTTIME
     *
     * @return the value of LOTTERY.T_LOTTERY.STARTTIME
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public Timestamp getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_LOTTERY.STARTTIME
     *
     * @param starttime the value for LOTTERY.T_LOTTERY.STARTTIME
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public void setStarttime(Timestamp starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_LOTTERY.ISSUE
     *
     * @return the value of LOTTERY.T_LOTTERY.ISSUE
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public String getIssue() {
        return issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_LOTTERY.ISSUE
     *
     * @param issue the value for LOTTERY.T_LOTTERY.ISSUE
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public void setIssue(String issue) {
        this.issue = issue == null ? null : issue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_LOTTERY.DRAWMONEY
     *
     * @return the value of LOTTERY.T_LOTTERY.DRAWMONEY
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public BigDecimal getDrawmoney() {
        return drawmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_LOTTERY.DRAWMONEY
     *
     * @param drawmoney the value for LOTTERY.T_LOTTERY.DRAWMONEY
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public void setDrawmoney(BigDecimal drawmoney) {
        this.drawmoney = drawmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_LOTTERY.DRAWNUM
     *
     * @return the value of LOTTERY.T_LOTTERY.DRAWNUM
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public BigDecimal getDrawnum() {
        return drawnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_LOTTERY.DRAWNUM
     *
     * @param drawnum the value for LOTTERY.T_LOTTERY.DRAWNUM
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public void setDrawnum(BigDecimal drawnum) {
        this.drawnum = drawnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_LOTTERY.DRAWNO
     *
     * @return the value of LOTTERY.T_LOTTERY.DRAWNO
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public String getDrawno() {
        return drawno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_LOTTERY.DRAWNO
     *
     * @param drawno the value for LOTTERY.T_LOTTERY.DRAWNO
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    public void setDrawno(String drawno) {
        this.drawno = drawno;
    }

	public BigDecimal getTotalsale() {
		return totalsale;
	}

	public void setTotalsale(BigDecimal totalsale) {
		this.totalsale = totalsale;
	}

	@Override
	public String toString() {
		return "LotteryModel [lotterid=" + lotterid + ", totalsale=" + totalsale + ", lid=" + lid + ", accumulated="
				+ accumulated + ", starttime=" + starttime + ", issue=" + issue + ", drawmoney=" + drawmoney
				+ ", drawnum=" + drawnum + ", drawno=" + drawno + "]";
	}

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}
}