package com.lottery.pojo;

import java.math.BigDecimal;
import java.sql.Timestamp;

public class NewsModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_NEWS.NEWSID
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    private Short newsid;
    private Timestamp adddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_NEWS.TITLE
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_NEWS.CONTENT
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_NEWS.NEWSID
     *
     * @return the value of LOTTERY.T_NEWS.NEWSID
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public Short getNewsid() {
        return newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_NEWS.NEWSID
     *
     * @param newsid the value for LOTTERY.T_NEWS.NEWSID
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public void setNewsid(Short newsid) {
        this.newsid = newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_NEWS.TITLE
     *
     * @return the value of LOTTERY.T_NEWS.TITLE
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_NEWS.TITLE
     *
     * @param title the value for LOTTERY.T_NEWS.TITLE
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_NEWS.CONTENT
     *
     * @return the value of LOTTERY.T_NEWS.CONTENT
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_NEWS.CONTENT
     *
     * @param content the value for LOTTERY.T_NEWS.CONTENT
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	public Timestamp getAdddate() {
		return adddate;
	}

	public void setAdddate(Timestamp adddate) {
		this.adddate = adddate;
	}

	@Override
	public String toString() {
		return "NewsModel [newsid=" + newsid + ", adddate=" + adddate + ", title=" + title + ", content=" + content
				+ "]";
	}
	
}