package com.lottery.pojo;

import java.math.BigDecimal;

public class TypeModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_LOTTERYTYPE.LID
     *
     * @mbggenerated Fri Oct 27 21:57:40 CST 2017
     */
    private Short lid;
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_LOTTERYTYPE.LOTYPENAME
     *
     * @mbggenerated Fri Oct 27 21:57:40 CST 2017
     */
    private String lotypename;

    @Override
	public String toString() {
		return "TypeModel [lid=" + lid + ", lotypename=" + lotypename + ", lotypedesc=" + lotypedesc + ", lotterdate="
				+ lotterdate + ", salemoney=" + salemoney + ", lottertime=" + lottertime + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_LOTTERYTYPE.LOTYPEDESC
     *
     * @mbggenerated Fri Oct 27 21:57:40 CST 2017
     */
    private String lotypedesc;
    private String lotterdate;
    private BigDecimal salemoney;
    private String lottertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_LOTTERYTYPE.LID
     *
     * @return the value of LOTTERY.T_LOTTERYTYPE.LID
     *
     * @mbggenerated Fri Oct 27 21:57:40 CST 2017
     */
   

    public String getLotterdate() {
		return lotterdate;
	}

	public void setLotterdate(String lotterdate) {
		this.lotterdate = lotterdate;
	}

	public BigDecimal getSalemoney() {
		return salemoney;
	}

	public void setSalemoney(BigDecimal salemoney) {
		this.salemoney = salemoney;
	}

	public String getLottertime() {
		return lottertime;
	}

	public void setLottertime(String lottertime) {
		this.lottertime = lottertime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_LOTTERYTYPE.LOTYPENAME
     *
     * @return the value of LOTTERY.T_LOTTERYTYPE.LOTYPENAME
     *
     * @mbggenerated Fri Oct 27 21:57:40 CST 2017
     */
    public String getLotypename() {
        return lotypename;
    }

    public Short getLid() {
		return lid;
	}

	public void setLid(Short lid) {
		this.lid = lid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_LOTTERYTYPE.LOTYPENAME
     *
     * @param lotypename the value for LOTTERY.T_LOTTERYTYPE.LOTYPENAME
     *
     * @mbggenerated Fri Oct 27 21:57:40 CST 2017
     */
    public void setLotypename(String lotypename) {
        this.lotypename = lotypename == null ? null : lotypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_LOTTERYTYPE.LOTYPEDESC
     *
     * @return the value of LOTTERY.T_LOTTERYTYPE.LOTYPEDESC
     *
     * @mbggenerated Fri Oct 27 21:57:40 CST 2017
     */
    public String getLotypedesc() {
        return lotypedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_LOTTERYTYPE.LOTYPEDESC
     *
     * @param lotypedesc the value for LOTTERY.T_LOTTERYTYPE.LOTYPEDESC
     *
     * @mbggenerated Fri Oct 27 21:57:40 CST 2017
     */
    public void setLotypedesc(String lotypedesc) {
        this.lotypedesc = lotypedesc == null ? null : lotypedesc.trim();
    }

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}
}