package com.lottery.pojo;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

public class UserModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_USER.USERID
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    private Short userid;
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_USER.USERNAME
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_USER.PASSWORD
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    
    private String truename;
    private Timestamp logindate;
    private Timestamp registerdate;
    public String getTruename() {
		return truename;
	}

	public void setTruename(String truename) {
		this.truename = truename;
	}

	public Timestamp getLogindate() {
		return logindate;
	}

	public void setLogindate(Timestamp logindate) {
		this.logindate = logindate;
	}

	public Timestamp getRegisterdate() {
		return registerdate;
	}

	public void setRegisterdate(Timestamp registerdate) {
		this.registerdate = registerdate;
	}

	private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_USER.PHONE
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_USER.ANUMBER
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    private String anumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_USER.APASSWORD
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    private Integer apassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_USER.ROLE
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    private Short role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY.T_USER.STATUS
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_USER.USERID
     *
     * @return the value of LOTTERY.T_USER.USERID
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public Short getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_USER.USERID
     *
     * @param userid the value for LOTTERY.T_USER.USERID
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public void setUserid(Short userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_USER.USERNAME
     *
     * @return the value of LOTTERY.T_USER.USERNAME
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_USER.USERNAME
     *
     * @param username the value for LOTTERY.T_USER.USERNAME
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_USER.PASSWORD
     *
     * @return the value of LOTTERY.T_USER.PASSWORD
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_USER.PASSWORD
     *
     * @param password the value for LOTTERY.T_USER.PASSWORD
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_USER.PHONE
     *
     * @return the value of LOTTERY.T_USER.PHONE
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_USER.PHONE
     *
     * @param phone the value for LOTTERY.T_USER.PHONE
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_USER.ANUMBER
     *
     * @return the value of LOTTERY.T_USER.ANUMBER
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public String getAnumber() {
        return anumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_USER.ANUMBER
     *
     * @param anumber the value for LOTTERY.T_USER.ANUMBER
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public void setAnumber(String anumber) {
        this.anumber = anumber == null ? null : anumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_USER.APASSWORD
     *
     * @return the value of LOTTERY.T_USER.APASSWORD
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public Integer getApassword() {
        return apassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_USER.APASSWORD
     *
     * @param apassword the value for LOTTERY.T_USER.APASSWORD
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public void setApassword(Integer apassword) {
        this.apassword = apassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_USER.ROLE
     *
     * @return the value of LOTTERY.T_USER.ROLE
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public Short getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_USER.ROLE
     *
     * @param role the value for LOTTERY.T_USER.ROLE
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public void setRole(Short role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY.T_USER.STATUS
     *
     * @return the value of LOTTERY.T_USER.STATUS
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY.T_USER.STATUS
     *
     * @param status the value for LOTTERY.T_USER.STATUS
     *
     * @mbggenerated Fri Oct 27 19:52:15 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

	@Override
	public String toString() {
		return "UserModel [userid=" + userid + ", username=" + username + ", truename=" + truename + ", logindate="
				+ logindate + ", registerdate=" + registerdate + ", password=" + password + ", phone=" + phone
				+ ", anumber=" + anumber + ", apassword=" + apassword + ", role=" + role + ", status=" + status + "]";
	}

	public BigDecimal getBalance() {
		return balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}
    
}