package com.lottery.service;

import java.math.BigDecimal;
import java.util.List;

import com.github.pagehelper.PageInfo;
import com.lottery.common.ServerResponse;
import com.lottery.pojo.BuyModel;
import com.lottery.pojo.DealModel;
import com.lottery.pojo.UserModel;
import com.lottery.vo.BuyVo;

public interface IBuyService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_BUY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int deleteByPrimaryKey(Short bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_BUY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int insert(BuyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_BUY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int insertSelective(BuyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_BUY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    BuyModel selectByPrimaryKey(Short bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_BUY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int updateByPrimaryKeySelective(BuyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_BUY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int updateByPrimaryKey(BuyModel record);
    
    /**
     * 按条件查询购奖信息
     * @param buy
     * @return
     */
    PageInfo<BuyVo> queryAll(BuyVo buy, int pageNum, int pageSize);

	ServerResponse save(BuyModel buy, UserModel user, DealModel deal);

	List<BuyModel> selectIsDraw();

	BigDecimal getTotalMoney(short userid);
}
