package com.lottery.service;

import java.math.BigDecimal;
import java.util.List;
import com.lottery.common.ServerResponse;
import com.lottery.pojo.DealModel;
import com.lottery.pojo.UserModel;
public interface IDealService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DEAL
     *
     * @mbggenerated Fri Oct 27 21:28:08 CST 2017
     */
    int deleteByPrimaryKey(Short did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DEAL
     *
     * @mbggenerated Fri Oct 27 21:28:08 CST 2017
     */
    int insert(DealModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DEAL
     *
     * @mbggenerated Fri Oct 27 21:28:08 CST 2017
     */
    ServerResponse insertSelective(UserModel user, DealModel deal, int flag);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DEAL
     *
     * @mbggenerated Fri Oct 27 21:28:08 CST 2017
     */
    DealModel selectByPrimaryKey(Short did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DEAL
     *
     * @mbggenerated Fri Oct 27 21:28:08 CST 2017
     */
    int updateByPrimaryKeySelective(DealModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DEAL
     *
     * @mbggenerated Fri Oct 27 21:28:08 CST 2017
     */
    int updateByPrimaryKey(DealModel record);
    
    /**
     * 按条件查询所有交易信息
     * @param deal
     * @return
     */
    ServerResponse queryAll(DealModel deal, int pageNum, int pageSize);

	BigDecimal getTotalMoney(short userid);

}
