package com.lottery.service;

import java.util.List;

import com.lottery.pojo.DrawDetailsModel;

public interface IDrawDetailsService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DRAWDETAILS
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    int deleteByPrimaryKey(Short ddid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DRAWDETAILS
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    int insert(DrawDetailsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DRAWDETAILS
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    int insertSelective(DrawDetailsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DRAWDETAILS
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    DrawDetailsModel selectByPrimaryKey(Short ddid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DRAWDETAILS
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    int updateByPrimaryKeySelective(DrawDetailsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DRAWDETAILS
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    int updateByPrimaryKey(DrawDetailsModel record);
    
    /**
     * 按条件查询开奖详情信息
     * @param details
     * @return
     */
    List<DrawDetailsModel> queryAll(DrawDetailsModel details);
}
