package com.lottery.service;

import java.util.List;

import com.github.pagehelper.PageInfo;
import com.lottery.common.ServerResponse;
import com.lottery.pojo.NewsModel;

public interface INewsService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_NEWS
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int deleteByPrimaryKey(Short newsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_NEWS
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int insert(NewsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_NEWS
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    ServerResponse insertSelective(NewsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_NEWS
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    NewsModel selectByPrimaryKey(Short newsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_NEWS
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int updateByPrimaryKeySelective(NewsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_NEWS
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int updateByPrimaryKey(NewsModel record);
    
    /**
     * 按条件查询新闻信息
     * @param news
     * @return
     */
    PageInfo<NewsModel> queryAll(NewsModel news, int pageNum, int pageSize);

	ServerResponse previous(short newsid);
	
	ServerResponse next(short newsid);
}
