package com.lottery.service;

import com.lottery.common.ServerResponse;
import com.lottery.common.ServerResponse;
import com.lottery.pojo.TypeModel;

public interface ITypeService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_LOTTERYTYPE
     *
     * @mbggenerated Fri Oct 27 21:57:40 CST 2017
     */
	ServerResponse deleteByPrimaryKey(Short lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_LOTTERYTYPE
     *
     * @mbggenerated Fri Oct 27 21:57:40 CST 2017
     */
    int insert(TypeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_LOTTERYTYPE
     *
     * @mbggenerated Fri Oct 27 21:57:40 CST 2017
     */
    ServerResponse insertSelective(TypeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_LOTTERYTYPE
     *
     * @mbggenerated Fri Oct 27 21:57:40 CST 2017
     */
    TypeModel selectByPrimaryKey(Short lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_LOTTERYTYPE
     *
     * @mbggenerated Fri Oct 27 21:57:40 CST 2017
     */
    ServerResponse updateByPrimaryKeySelective(TypeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_LOTTERYTYPE
     *
     * @mbggenerated Fri Oct 27 21:57:40 CST 2017
     */
    int updateByPrimaryKey(TypeModel record);
    
    /**
     * 按条件查询彩票信息
     * @param type
     * @return
     */
    ServerResponse queryAll(TypeModel type,int pageNum,int pageSize);
    ServerResponse queryByUsername(String lotypename,TypeModel type,int pageNum,int pageSize);

	ServerResponse undercarriage(Short lid);

	ServerResponse live(Short lid);


}
