package com.lottery.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lottery.pojo.BuyModel;
import com.lottery.vo.BuyVo;

public interface BuyModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_BUY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int deleteByPrimaryKey(Short bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_BUY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int insert(BuyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_BUY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int insertSelective(BuyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_BUY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    BuyModel selectByPrimaryKey(Short bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_BUY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int updateByPrimaryKeySelective(BuyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_BUY
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int updateByPrimaryKey(BuyModel record);
    
    /**
     * 按条件查询购奖信息
     * @param buy
     * @return
     */
    List<BuyVo> queryAll(BuyVo buy);

    /**
     * 根据彩种和期号查询购买此期彩票的用户
     * @param lid
     * @param issue
     * @param lotterid
     * @return
     */
	List<BuyModel> selectByLottery(@Param("lid") short lid, @Param("issue") String issue);

	/**
	 * 根据购买号码修改是否中奖
	 * @param buyNo
	 * @param isDraw
	 * @return
	 */
	int updateIsDrawByBuyNo(@Param("buyno") String buyNo, @Param("isdraw") String isDraw);

	/**
	 * 查询中奖情况
	 * @return
	 */
	List<BuyModel> selectIsDraw();

	/**
	 * 查询购买彩票总金额
	 * @param userid
	 * @return
	 */
	BigDecimal selectSumMoney(short userid);
}