package com.lottery.dao;

import java.math.BigDecimal;
import java.util.List;

import com.lottery.pojo.DealModel;
import com.lottery.pojo.UserModel;

public interface DealModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DEAL
     *
     * @mbggenerated Fri Oct 27 21:28:08 CST 2017
     */
    int deleteByPrimaryKey(Short dealid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DEAL
     *
     * @mbggenerated Fri Oct 27 21:28:08 CST 2017
     */
    int insert(DealModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DEAL
     *
     * @mbggenerated Fri Oct 27 21:28:08 CST 2017
     */
    int insertSelective(DealModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DEAL
     *
     * @mbggenerated Fri Oct 27 21:28:08 CST 2017
     */
    DealModel selectByPrimaryKey(Short dealid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DEAL
     *
     * @mbggenerated Fri Oct 27 21:28:08 CST 2017
     */
    int updateByPrimaryKeySelective(DealModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DEAL
     *
     * @mbggenerated Fri Oct 27 21:28:08 CST 2017
     */
    int updateByPrimaryKey(DealModel record);
    
    /**
     * 按条件查询所有交易信息
     * @param deal
     * @return
     */
    List<DealModel> queryAll(DealModel deal);

	BigDecimal selectSumDrawMoney(short userid);
   
    /**
     * 按交易金额查询交易信息
     * @param deal
     * @return
     */
  /*  UserModel selectByDealMoney(Decimal money);*/
}