package com.lottery.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lottery.pojo.DrawDetailsModel;

public interface DrawDetailsModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DRAWDETAILS
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    int deleteByPrimaryKey(Short ddid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DRAWDETAILS
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    int insert(DrawDetailsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DRAWDETAILS
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    int insertSelective(DrawDetailsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DRAWDETAILS
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    DrawDetailsModel selectByPrimaryKey(Short ddid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DRAWDETAILS
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    int updateByPrimaryKeySelective(DrawDetailsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_DRAWDETAILS
     *
     * @mbggenerated Sat Oct 28 10:50:35 CST 2017
     */
    int updateByPrimaryKey(DrawDetailsModel record);
    
    /**
     * 按条件查询开奖详情信息
     * @param details
     * @return
     */
    List<DrawDetailsModel> queryAll(DrawDetailsModel details);

    /**
     * 根据彩种id和期号查询此期彩票详情
     * @param lid
     * @param issue
     * @return
     */
	List<DrawDetailsModel> selectDetailByLidAndIssue(@Param("lid") short lid, @Param("issue") String issue);

	/**
	 * 根据彩票id与奖项名称查询详情id与中奖人数
	 * @param lotterid
	 * @param string
	 * @return
	 */
	DrawDetailsModel selectByLotteridAndPrize(@Param("lotterid") Short lotterid, @Param("prize") String prize);

}