package com.lottery.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import com.lottery.pojo.LotteryModel;
import com.lottery.vo.LotteryVo;

public interface LotteryModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_LOTTERY
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    int deleteByPrimaryKey(Short lotterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_LOTTERY
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    int insert(LotteryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_LOTTERY
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    int insertSelective(LotteryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_LOTTERY
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    LotteryModel selectByPrimaryKey(Short lotterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_LOTTERY
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    int updateByPrimaryKeySelective(LotteryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_LOTTERY
     *
     * @mbggenerated Sat Oct 28 09:17:31 CST 2017
     */
    int updateByPrimaryKey(LotteryModel record);
    
    /**
     * 按条件查询所有彩票信息
     * @param lottory
     * @return
     */
    List<LotteryVo> queryAll(LotteryModel lottory);

    /**
     * 根据采种id得到此类彩票最新的一期期号
     * @param lid
     * @return
     */
	String selectIssue(Short lid);

	/**
	 * 根据彩种id与期号获取开奖日期
	 * @param lid
	 * @param issue
	 * @return
	 */
	String selectStartTimeByIssueAndLid(@Param("lid") Short lid, @Param("issue") String issue);

	/**
	 * 通过彩种id与期号查询滚存、id与总售价
	 * @param lid
	 * @param issue
	 * @return
	 */
	LotteryModel selectByLidAndIssue(@Param("lid") Short lid, @Param("issue") String issue);

	/**
	 * 根据彩种id和期号更新
	 * @param lottery
	 * @return
	 */
	int updateByLidAndIssue(LotteryModel lottery);
	
	/**
	 * 按期号分组查询
	 * @return
	 */
	List<LotteryModel> selectIssueByGroup();

	/**
	 * 根据彩种id删除彩票
	 * @param lid
	 * @return
	 */
	int deleteByLid(Short lid);

	/**
	 * 根据彩种id与状态查询彩票数量
	 * @param lid
	 * @return
	 */
	int selectByLidAndStatus(Short lid);
}