package com.lottery.dao;

import java.util.List;

import com.lottery.pojo.NewsModel;

public interface NewsModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_NEWS
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int deleteByPrimaryKey(Short newsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_NEWS
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int insert(NewsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_NEWS
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int insertSelective(NewsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_NEWS
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    NewsModel selectByPrimaryKey(Short newsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_NEWS
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int updateByPrimaryKeySelective(NewsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY.T_NEWS
     *
     * @mbggenerated Sat Oct 28 11:11:04 CST 2017
     */
    int updateByPrimaryKey(NewsModel record);
    
    /**
     * 按条件查询新闻信息
     * @param news
     * @return
     */
    List<NewsModel> queryAll(NewsModel news);

    /**
     * 查询上一条新闻
     * @return
     */
	List<NewsModel> previous();
}